AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  LinkedInJobNotifierFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main          # Entry point of your Go program
      Runtime: go1.x         # Specify Go runtime
      CodeUri: ./cmd/lambda/main/  # Directory containing the Go binary
      MemorySize: 128
      Timeout: 10
      Events:
        LinkedInJobNotifierApiEvent:
          Type: Api
          Properties:
            Path: /notify
            Method: POST
